disabled_rules:
  - file_length
  - force_cast
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - opening_brace
  - trailing_comma
  - type_body_length
analyzer_rules:
  - typesafe_array_init
  - unused_declaration
  - unused_import
opt_in_rules:
  - array_init
  - closure_spacing
  - empty_collection_literal
  # Disabled as there are too many false positives
  #- no_magic_numbers
  - empty_count
  - empty_string
  - sorted_imports
  - yoda_condition
