disabled_rules:
  - file_length
  - force_cast
  - function_body_length
  - identifier_name
  - line_length
  - opening_brace
  - trailing_comma
  - type_body_length
  - closure_parameter_position
analyzer_rules:
  - typesafe_array_init
  - unused_declaration
  - unused_import
opt_in_rules:
  - array_init
  - closure_spacing
  - empty_collection_literal
  - empty_count
  - empty_string
  - legacy_objc_type
  - let_var_whitespace
  # Disabled as there are too many false positives
  # - no_magic_numbers
  - sorted_imports
  - trailing_closure
  - yoda_condition
