disabled_rules:
  - identifier_name
  - type_name
  - opening_brace
  - trailing_comma
  - force_cast
  - line_length
  - large_tuple
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - force_try