public protocol CodeVisitor {
  func visitSourceFile(file: SourceFile)
  func visitBuildDefinition(node: BuildDefinition)
  func visitErrorNode(node: ErrorNode)
  func visitSelectionStatement(node: SelectionStatement)
  func visitBreakStatement(node: BreakNode)
  func visitContinueStatement(node: ContinueNode)
  func visitIterationStatement(node: IterationStatement)
  func visitAssignmentStatement(node: AssignmentStatement)
  func visitFunctionExpression(node: FunctionExpression)
  func visitArgumentList(node: ArgumentList)
  func visitKeywordItem(node: KeywordItem)
  func visitConditionalExpression(node: ConditionalExpression)
  func visitUnaryExpression(node: UnaryExpression)
  func visitSubscriptExpression(node: SubscriptExpression)
  func visitMethodExpression(node: MethodExpression)
  func visitIdExpression(node: IdExpression)
  func visitBinaryExpression(node: BinaryExpression)
  func visitStringLiteral(node: StringLiteral)
  func visitArrayLiteral(node: ArrayLiteral)
  func visitBooleanLiteral(node: BooleanLiteral)
  func visitIntegerLiteral(node: IntegerLiteral)
  func visitDictionaryLiteral(node: DictionaryLiteral)
  func visitKeyValueItem(node: KeyValueItem)
}
