name: Build on platforms
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  fedora:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build on Fedora 37
        run: |
          sudo apt purge -y podman
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update
          sudo apt-get -y install podman
          podman --version
          DOCKER_BUILDKIT=1 docker build --file Dockerfile --output out .
          sudo cp out/Fedora37.zip /Fedora37.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Fedora37.zip
          path: /Fedora37.zip
  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build on MacOS 12
        run: |
          swift build
          swift test
          ./.build/debug/Swift-MesonLSP --test TestCases/BasicTests/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/Options/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/ComputeSubdirs/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/ComputeSetVariable/meson.build
          ./do_meson_tests.sh
          ./run_regression_tests.sh
          yes | brew install mercurial
          ./run_wrap_tests.sh
          swift build -c release
          mkdir -p ${{ github.workspace }}/Artifacts
          sudo cp .build/release/Swift-MesonLSP ${{ github.workspace }}/Artifacts/Swift-MesonLSP
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS12.zip
          path: ${{ github.workspace }}/Artifacts
  ubuntu1804:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build on Ubuntu 18.04
        run: |
          sudo apt purge -y podman
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update
          sudo apt-get -y install podman
          podman --version
          DOCKER_BUILDKIT=1 docker build --file Dockerfile.ubuntu1804 --output out .
          sudo cp out/Ubuntu18.04.zip /Ubuntu18.04.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Ubuntu18.04.zip
          path: /Ubuntu18.04.zip
  ubuntu2004:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build on Ubuntu 20.04
        run: |
          sudo apt purge -y podman
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update
          sudo apt-get -y install podman
          podman --version
          DOCKER_BUILDKIT=1 docker build --file Dockerfile.ubuntu2004 --output out .
          sudo cp out/Ubuntu20.04.zip /Ubuntu20.04.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Ubuntu20.04.zip
          path: /Ubuntu20.04.zip
  ubuntu2204:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build on Ubuntu 22.04
        run: |
          sudo apt purge -y podman
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update
          sudo apt-get -y install podman
          podman --version
          DOCKER_BUILDKIT=1 docker build --file Dockerfile.ubuntu --output out .
          sudo cp out/Ubuntu22.04.zip /Ubuntu22.04.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Ubuntu22.04.zip
          path: /Ubuntu22.04.zip
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
      - name: Run integration tests
        run: |
          sudo apt install -y mercurial
          swift build
          ./.build/debug/Swift-MesonLSP --test TestCases/BasicTests/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/Options/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/ComputeSubdirs/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/ComputeSetVariable/meson.build
          ./do_meson_tests.sh
          ./run_wrap_tests.sh
          git clone https://github.com/mesonbuild/wrapdb
          mkdir wo
          for i in wrapdb/subprojects/*.wrap; do .build/debug/Swift-MesonLSP --wrap $i --wrap-package-files "./wrapdb/subprojects/packagefiles" --wrap-output ./wo/ || exit 1; done
  regressiontests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run regression tests
        run: |
          swift build -c release --static-swift-stdlib
          ./run_regression_tests.sh
  profiling:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -c release --static-swift-stdlib
      - name: Profile the code
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          sudo apt install -y heaptrack git jq
          swift build -c release --static-swift-stdlib
          ./collect_perf_data.py --ci .build/release/Swift-MesonLSP ${{ github.sha }} | jq >/tmp/${{ github.sha }}.json
          cat /tmp/${{ github.sha }}.json
          git clone https://.:${{ secrets.API_TOKEN_GITHUB }}@github.com/JCWasmx86/ProfilingData target
          cp /tmp/${{ github.sha }}.json target
          cd target
          git config --global user.email "JCWasmx86@t-online.de"
          git config --global user.name "JCWasmx86"
          git add .
          git commit -m "Push data for ${{ github.sha }}"
          git push
  build-debs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run regression tests
        run: |
          swift build -c release --static-swift-stdlib
          sudo apt purge -y podman
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update
          sudo apt-get -y install podman dpkg
          podman --version
          DOCKER_BUILDKIT=1 docker build --file Dockerfile.ubuntu1804 --output out .
          DOCKER_BUILDKIT=1 docker build --file Dockerfile.ubuntu2004 --output out1 .
          DOCKER_BUILDKIT=1 docker build --file Dockerfile.ubuntu --output out2 .
          cd out
          unzip Ubuntu18.04.zip
          cd ../out1
          unzip Ubuntu20.04.zip
          cd ../out2
          unzip Ubuntu22.04.zip
          cd ..
          ./debian/build_debs.sh
      - uses: actions/upload-artifact@v3
        with:
          name: Swift-MesonLSP-ubuntu-18.04.deb
          path: /Swift-MesonLSP-ubuntu-18.04.deb
      - uses: actions/upload-artifact@v3
        with:
          name: Swift-MesonLSP-ubuntu-20.04.deb
          path: /Swift-MesonLSP-ubuntu-20.04.deb
      - uses: actions/upload-artifact@v3
        with:
          name: Swift-MesonLSP-ubuntu-22.04.deb
          path: /Swift-MesonLSP-ubuntu-22.04.deb