name: Build on platforms
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  fedora_in_container:
    strategy:
      matrix:
        version: [38, 39]
    runs-on: ubuntu-latest
    container:
      image: fedora:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v1
      - name: Build on Fedora ${{ matrix.version }}
        run: |
          sudo dnf install ninja-build gcc g++ git pip libcurl-devel glibc-static libarchive-devel gtest gtest-devel libpkgconf-devel libuuid-devel uuid python3-pip pkgconf-pkg-config -y
          pip install meson
          sudo dnf clean all
          ./scripts/ci_create_zip.sh Fedora${{ matrix.version }}
      - uses: actions/upload-artifact@v3
        with:
          name: Fedora${{ matrix.version }}.zip
          path: /Fedora${{ matrix.version }}.zip
