name: Copy DLL Files

on:
  push:
    branches:
      - main
jobs:
  copy_dll_files:
    runs-on: windows-latest

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.3-release
          tag: 5.7.3-RELEASE
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy DLL files
        shell: powershell
        run: |
          Get-ChildItem -Path C:\ -Filter BlocksRuntime.dll
          $sourcePaths = @('C:\', 'D:\')
          $destinationPath = $env:GITHUB_WORKSPACE
          $dllFiles = @(
            'BlocksRuntime.dll',
            'dispatch.dll',
            'Foundation.dll',
            'icudt69.dll',
            'icuin69.dll',
            'icuuc69.dll',
            'swift_Concurrency.dll',
            'swiftCore.dll',
            'swiftCRT.dll',
            'swiftDispatch.dll',
            'swiftWinSDK.dll'
          )
          foreach ($path in $sourcePaths) {
            foreach ($dll in $dllFiles) {
              $file = Get-ChildItem -Path $path -Filter $dll -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
              if ($file) {
                $destinationFilePath = Join-Path -Path $destinationPath -ChildPath $file.Name
                Copy-Item -Path $file.FullName -Destination $destinationFilePath -Force
                Write-Host "Copied $($file.FullName) to $($destinationFilePath)"
              }
            }
          }
      - name: Copy foo.exe
        run: |
          $sourceFilePath = "$env:GITHUB_WORKSPACE\Benchmarks\script.js"
          $destinationFilePath = "$env:GITHUB_WORKSPACE\foo.exe"
          Copy-Item -Path $sourceFilePath -Destination $destinationFilePath -Force
          Write-Host "Copied foo.exe to $destinationFilePath"
      - name: Create zip archive
        run: |
          $zipPath = "$env:GITHUB_WORKSPACE\build.zip"
          Compress-Archive -Path "$env:GITHUB_WORKSPACE\*.dll" "$env:GITHUB_WORKSPACE\*.exe" -DestinationPath $zipPath
          Write-Host "Created zip archive: $zipPath"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: $env:GITHUB_WORKSPACE\build.zip
