name: Copy DLL Files

on:
  push:
    branches:
      - main
jobs:
  copy_dll_files:
    runs-on: windows-latest

    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.3-release
          tag: 5.7.3-RELEASE
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy DLL files
        shell: powershell
        run: |
          $destinationPath = $env:GITHUB_WORKSPACE/Artifacts
          mkdir $destinationFilePath
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\BlocksRuntime.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\dispatch.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\Foundation.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\swift_Concurrency.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\swiftCore.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\swiftCRT.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\swiftDispatch.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\runtime-development\\usr\\bin\\swiftWinSDK.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\icu-69.1\\usr\\bin\\icudt69.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\icu-69.1\\usr\\bin\\icuin69.dll" -Destination $destinationFilePath -Force
          Copy-Item "C:\\Program Files\\swift\\icu-69.1\\usr\\bin\\icuuc69.dll" -Destination $destinationFilePath -Force
      - name: Copy foo.exe
        run: |
          $sourceFilePath = "$env:GITHUB_WORKSPACE\Benchmarks\script.js"
          $destinationFilePath = "$env:GITHUB_WORKSPACE\Artifacts\foo.exe"
          Copy-Item -Path $sourceFilePath -Destination $destinationFilePath -Force
      - name: Create license bundle
        shell: bash
        run: |
          ./scripts/create_license_bundle.sh
          cp 3rdparty.txt Artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Windows.zip
          path: ${{ github.workspace }}/Artifacts
