name: Coverage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Collect coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          sudo apt install -y lcov mercurial
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          llvm-profdata-17 --help
          llvm-cov-17 --help
          cargo --help
          ./scripts/collect_coverage.sh
          bash <(curl -s https://codecov.io/bash)