name: Collect Coverage
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: fedora:39
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Collecting coverage
        shell: bash
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: |
          sudo dnf install lcov zip ninja-build google-benchmark-devel gcc g++ git pip libcurl-devel glibc-static libarchive-devel gtest gtest-devel libpkgconf-devel libuuid-devel uuid python3-pip pkgconf-pkg-config mercurial subversion -y
          pip install meson pygls lsprotocol
          sudo dnf clean all
          meson _build -Db_coverage=true
          ninja -C _build test
          echo "ignore_errors=mismatch,negative" > ~/.lcovrc
          ninja -C _build coverage || true
          cp _build/meson-logs/coverage.info out.lcov
          bash <(curl -s https://codecov.io/bash)
