name: Formatting Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Check if formatting is correct
        run: |
          git clone https://github.com/apple/swift-format
          cd swift-format
          swift build
          cd ..
          ./swift-format/.build/debug/swift-format -i --recursive Package.swift Sources/ Tests
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -a -m "Failed" || exit 0
          git diff HEAD~1 | cat