name: MacOS-CI

on:
  push:
  workflow_dispatch:

# Just check that it builds and the test pass. I don't have MacOS, but
# assuming it compiles, it should there, as I didn't do Linux
# specific things
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          swift build
          swift test
          ./.build/debug/Swift-MesonLSP --test TestCases/BasicTests/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/Options/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/ComputeSubdirs/meson.build
          ./.build/debug/Swift-MesonLSP --test TestCases/ComputeSetVariable/meson.build
          ./do_meson_tests.sh
          ./run_regression_tests.sh
          swift build -c release
          zip -9jpr Swift-MesonLSP.zip .build/release/Swift-MesonLSP
          mkdir -p ${{ github.workspace }}/Artifacts
          sudo cp Swift-MesonLSP.zip ${{ github.workspace }}/Artifacts/Swift-MesonLSP-MacOS.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Swift-MesonLSP-MacOS.zip
          path: ${{ github.workspace }}/Artifacts