name: Profiling

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -c release --static-swift-stdlib
      - name: Run profiling tests
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          sudo apt install -y heaptrack git
          heaptrack_print --help
          swift build -c release --static-swift-stdlib
          ./collect_perf_data.py --ci .build/release/Swift-MesonLSP ${{ github.sha }} >/tmp/${{ github.sha }}.json
          cat /tmp/${{ github.sha }}.json
          git clone https://.:${{ secrets.API_TOKEN_GITHUB }}@github.com/JCWasmx86/ProfilingData target
          cp /tmp/${{ github.sha }}.json target
          cd target
          git config --global user.email "JCWasmx86@t-online.de"
          git config --global user.name "JCWasmx86"
          git add .
          git commit -m "Automatic publish from github.com/project"
          git push