name: Regression Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Run regression tests
        run: |
          swift build -c release --static-swift-stdlib
          ./run_regression_tests.sh
