name: Release-Upload

on:
  release:
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build -c release --static-swift-stdlib
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: .build/release/Swift-MesonLSP
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}