name: Release-Upload

on:
  release:
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          #swift build -c release --static-swift-stdlib
          mkdir -p .build/release
          touch .build/release/Swift-MesonLSP
          zip Swift-MesonLSP.zip .build/release/Swift-MesonLSP
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: Swift-MesonLSP.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}