name: Swift-Format check
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix UID
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Lint
        uses: mtgto/swift-format-action@main
        with:
          configuration_file: .swift-format
          all_files: true
          max_warnings: -1