name: Windows-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows-573:
    runs-on: windows-2019
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.3-release
          tag: 5.7.3-RELEASE
      - name: Enable long paths on Windows
        shell: powershell
        run: |
          Set-ItemProperty -Path "HKLM:\\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1
      - uses: actions/checkout@v3
      - run: |
          cd ..\..
          git clone https://github.com/JCWasmx86/Swift-MesonLSP b
          cd b
          swift build --static-swift-stdlib -c debug
          swift test
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/BasicTests/meson.build
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/Options/meson.build
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/ComputeSubdirs/meson.build
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/ComputeSetVariable/meson.build
          mkdir __wrap_target
          .\.build\debug\Swift-MesonLSP.exe --wrap Wraps\rustc-demangle.wrap --wrap Wraps/libswiftdemangle.wrap --wrap Wraps\libswiftdemangle2.wrap --wrap Wraps\miniz.wrap --wrap Wraps\turtle.wrap --wrap Wraps\sqlite.wrap --wrap Wraps\pango.wrap --wrap Wraps\turtle2.wrap --wrap Wraps\turtle3.wrap --wrap Wraps\rubberband.wrap --wrap-output __wrap_target --wrap-package-files .\Wraps\packagefiles
  windows-58:
    runs-on: windows-2019
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.8-release
          tag: 5.8-RELEASE
      - name: Enable long paths on Windows
        shell: powershell
        run: |
          Set-ItemProperty -Path "HKLM:\\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1
      - uses: actions/checkout@v3
      - run: |
          cd ..\..
          git clone https://github.com/JCWasmx86/Swift-MesonLSP b
          cd b
          swift build --static-swift-stdlib -c debug
          swift test
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/BasicTests/meson.build
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/Options/meson.build
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/ComputeSubdirs/meson.build
          .\.build\debug\Swift-MesonLSP.exe --test TestCases/ComputeSetVariable/meson.build
          mkdir __wrap_target
          .\.build\debug\Swift-MesonLSP.exe --wrap Wraps\rustc-demangle.wrap --wrap Wraps/libswiftdemangle.wrap --wrap Wraps\libswiftdemangle2.wrap --wrap Wraps\miniz.wrap --wrap Wraps\turtle.wrap --wrap Wraps\sqlite.wrap --wrap Wraps\pango.wrap --wrap Wraps\turtle2.wrap --wrap Wraps\turtle3.wrap --wrap Wraps\rubberband.wrap --wrap-output __wrap_target --wrap-package-files .\Wraps\packagefiles
