name: Windows-CI

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.3-release
          tag: 5.7.3-RELEASE

      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
