name: Windows-CI

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.3-release
          tag: 5.7.3-RELEASE
      - name: Enable long paths on Windows
        shell: powershell
        run: |
          Set-ItemProperty -Path "HKLM:\\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1
      - uses: actions/checkout@v3
      - run: |
          swift build -v || echo Command Failed
          (Get-Content -ReadCount 0 .build/checkouts/sourcekit-lsp/Package.swift) -replace 'static', 'dynamic' | Set-Content .build/checkouts/sourcekit-lsp/Package.swift -WhatIf
          Remove-Item -LiteralPath ".build/x86_64-unknown-windows-msvc" -Force -Recurse
          swift build
          swift test
