name: Windows-CI

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.3-release
          tag: 5.7.3-RELEASE
      - name: Enable long paths on Windows
        shell: powershell
        run: |
          Set-ItemProperty -Path "HKLM:\\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1
      - uses: actions/checkout@v3
      - run: |
          cscript /?
          swift build -v || echo Command Failed
          cscript //NoLogo .ci\sed.vbs s/(static)/(dynamic)/ < .build/checkouts/sourcekit-lsp/Package.swift > outfile.txt
          type outfile.txt
          copy /y outfile.txt .build/checkouts/sourcekit-lsp/Package.swift
          swift build
          swift test
